SET standard_conforming_strings = ON;
DROP TABLE IF EXISTS "qwc_geodb"."cittadini_puntiformi" CASCADE;
BEGIN;
CREATE TABLE "qwc_geodb"."cittadini_puntiformi"();
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "cittadini_puntiformi_pk" PRIMARY KEY;
SELECT AddGeometryColumn('qwc_geodb','cittadini_puntiformi','wkb_geometry',4326,'POINT',2);
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "fid" NUMERIC(20,0);
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "id_ass" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "nome_cognome" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "sei_sul_posto" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "tipo_segnalazione" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "eri_presente" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "hai_segnalato_autorita" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "quale_autorita" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "ora_inizio_evento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "ora_fine_evento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "località_evento" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "indirizzo_evento" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "all_1" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "all_2" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "all_3" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "all_4" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "all_5" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "all_6" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "note_1" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "note_2" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "note_3" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "note_4" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "note_5" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "note_6" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "longitudine" FLOAT8;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "latitudine" FLOAT8;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "verifica_effettuata" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "token" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "ora_inserimento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "esito_verifica" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "tua_mail" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_puntiformi" ADD COLUMN "tuo_telefono" VARCHAR;
CREATE INDEX "cittadini_puntiformi_wkb_geometry_geom_idx" ON "qwc_geodb"."cittadini_puntiformi" USING GIST ("wkb_geometry");
COMMIT;
