SET standard_conforming_strings = ON;
DROP TABLE IF EXISTS "qwc_geodb"."cittadini_linee" CASCADE;
BEGIN;
CREATE TABLE "qwc_geodb"."cittadini_linee"();
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "cittadini_linee_pk" PRIMARY KEY;
SELECT AddGeometryColumn('qwc_geodb','cittadini_linee','wkb_geometry',4326,'LINESTRING',2);
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "fid" NUMERIC(20,0);
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "id_ass" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "nome_cognome" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "sei_sul_posto" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "tipo_segnalazione" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "eri_presente" timestamp with time zone;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "hai_segnalato_autorita" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "quale_autorita" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "ora_inizio_evento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "ora_fine_evento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "località_evento" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "indirizzo_evento" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "all_1" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "all_2" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "all_3" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "all_4" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "all_5" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "all_6" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "note_1" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "note_2" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "note_3" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "note_4" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "note_5" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "note_6" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "lunghezza" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "verifica_effettuata" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "token" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "ora_inserimento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "esito_verifica" BOOLEAN;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "tua_mail" VARCHAR;
ALTER TABLE "qwc_geodb"."cittadini_linee" ADD COLUMN "tuo_telefono" VARCHAR;
INSERT INTO "qwc_geodb"."cittadini_linee" ("wkb_geometry", "fid", "id_ass", "nome_cognome", "sei_sul_posto", "tipo_segnalazione", "eri_presente", "hai_segnalato_autorita", "quale_autorita", "ora_inizio_evento", "ora_fine_evento", "località_evento", "indirizzo_evento", "all_1", "all_2", "all_3", "all_4", "all_5", "all_6", "note_1", "note_2", "note_3", "note_4", "note_5", "note_6", "lunghezza", "verifica_effettuata", "token", "ora_inserimento", "esito_verifica", "tua_mail", "tuo_telefono") VALUES ('0102000020E610000007000000807F3CA7CC582C402F2CD37204F54240EF6E695397592C40E11A60EABAF44240D92CF4EB075A2C408D3D003AA3F44240EC627D2E395B2C40B7A6B3AA81F44240053F90A7645D2C40D89DBA5A73F4424029EF8ECB095E2C40AA355B923CF442401F9836C9B35B2C4032F3980C18F44240', 1, NULL, 'io', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '');
CREATE INDEX "cittadini_linee_wkb_geometry_geom_idx" ON "qwc_geodb"."cittadini_linee" USING GIST ("wkb_geometry");
COMMIT;
