SET standard_conforming_strings = ON;
DROP TABLE IF EXISTS "qwc_geodb"."istituzionali_superfici" CASCADE;
BEGIN;
CREATE TABLE "qwc_geodb"."istituzionali_superfici"();
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "istituzionali_superfici_pk" PRIMARY KEY;
SELECT AddGeometryColumn('qwc_geodb','istituzionali_superfici','wkb_geometry',4326,'POLYGON',4);
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "fid" NUMERIC(20,0);
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "nome_ente_segnalatore" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "referente_segnalatore" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "comune_interessato" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "data_trasmissione_informazioni" date;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "data_acquisizione_informazioni" date;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "n_verbale" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "data_evento" date;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "ora_inizio_evento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "ora_fine_evento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "località_evento" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "indirizzo_evento" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "all_1" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "all_2" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "all_3" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "all_4" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "all_5" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "all_6" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "note_1" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "note_2" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "note_3" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "note_4" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "note_5" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "note_6" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "superficie_in_mq" FLOAT8;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "perimetro_in_m" FLOAT8;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "verifica_effettuata" BOOLEAN;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "token" VARCHAR;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "ora_inserimento" timestamp with time zone;
ALTER TABLE "qwc_geodb"."istituzionali_superfici" ADD COLUMN "esito_verifica" BOOLEAN;
CREATE INDEX "istituzionali_superfici_wkb_geometry_geom_idx" ON "qwc_geodb"."istituzionali_superfici" USING GIST ("wkb_geometry");
COMMIT;
