SET standard_conforming_strings = ON;
DROP TABLE IF EXISTS "public"."istituzionali_puntiformi" CASCADE;
BEGIN;
CREATE TABLE "public"."istituzionali_puntiformi"();
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "istituzionali_puntiformi_pk" PRIMARY KEY;
SELECT AddGeometryColumn('public','istituzionali_puntiformi','wkb_geometry',4326,'POINT',2);
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "fid" NUMERIC(20,0);
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "nome_ente_segnalatore" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "referente_segnalatore" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "comune_interessato" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "data_trasmissione_informazioni" date;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "data_acquisizione_informazioni" date;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "n_verbale" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "data_evento" date;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "ora_inizio_evento" timestamp with time zone;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "ora_fine_evento" timestamp with time zone;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "località_evento" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "indirizzo_evento" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "all_1" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "all_2" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "all_3" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "all_4" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "all_5" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "all_6" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "note_1" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "note_2" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "note_3" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "note_4" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "note_5" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "note_6" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "longitudine" FLOAT8;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "latitudine" FLOAT8;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "verifica_effettuata" BOOLEAN;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "token" VARCHAR;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "ora_inserimento" timestamp with time zone;
ALTER TABLE "public"."istituzionali_puntiformi" ADD COLUMN "esito_verifica" BOOLEAN;
CREATE INDEX "istituzionali_puntiformi_wkb_geometry_geom_idx" ON "public"."istituzionali_puntiformi" USING GIST ("wkb_geometry");
COMMIT;
