SET standard_conforming_strings = ON;
DROP TABLE IF EXISTS "public"."mappatura_associazioni" CASCADE;
BEGIN;
CREATE TABLE "public"."mappatura_associazioni"();
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "mappatura_associazioni_pk" PRIMARY KEY;
SELECT AddGeometryColumn('public','mappatura_associazioni','wkb_geometry',4326,'POINT',3);
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "fid" NUMERIC(20,0);
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "id_ass" NUMERIC(10,0);
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "nome_associazione" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "comune" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "attivita_prevalente" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "motivo_interesse" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "disponibilità_feedback" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "autorizzo_visualizzazione_su_mappa" BOOLEAN;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "indirizzo" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "indirizzo_2" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "citta" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "cap" NUMERIC(10,0);
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "nazione" NUMERIC(10,0);
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "mail_di_riferimento_aperto_al_pubblico" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "sito_web_o_social" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "nome_referente" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "cognome_referente" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "telefono" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "email_referente" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "ora_invio" timestamp with time zone;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "token" timestamp with time zone;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "logo" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "note1" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "note2" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "note3" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "stato_regione_provincia" VARCHAR;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "verifica_dati" BOOLEAN;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "data_ora_verifica_dati" timestamp with time zone;
ALTER TABLE "public"."mappatura_associazioni" ADD COLUMN "operatore_verifica" VARCHAR;
CREATE INDEX "mappatura_associazioni_wkb_geometry_geom_idx" ON "public"."mappatura_associazioni" USING GIST ("wkb_geometry");
COMMIT;
